### ISSUE TITLE
Building functions fails to copy invoker layer for a specific image

### ISSUE THREAD

**Issue by trisberg** [projectriff/builder#34] opened 2019-02-18 19:39 UTC
Somehow I have an image in my registry that causes build some issues. I've copied the image to dockerhub as `trisberg/hello:bad`.

If I try to build a function using the same image:tag then I get en error when the function starts since the invoker layer is missing.

```
Aruba:~ trisberg$ riff function create hello --git-repo https://github.com/projectriff-samples/hello.js --artifact hello.js --image trisberg/hello:bad --verbose
Waiting for LatestCreatedRevisionName
LatestCreatedRevisionName available: hello-00001
Waiting on function creation: function creation incomplete: service status unknown: RevisionMissing: Configuration "hello" is waiting for a Revision to become ready.
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Trying group of 5...
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Output: NPM Buildpack ========
default/hello-00001-pod-507033[build-step-detect]: no "package.json" found at: /workspace/package.json
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 ======== Results ========
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry OpenJDK Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Node.js Buildpack: pass
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 Cloud Foundry Build System Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 NPM Buildpack: skip
default/hello-00001-pod-507033[build-step-detect]: 2019/02/18 19:33:36 riff Buildpack: pass
default/hello-00001-pod-507033[build-step-analyze]: 2019/02/18 19:33:39 writing metadata for uncached layer 'io.projectriff.riff/function'
default/hello-00001-pod-507033[build-step-analyze]: 2019/02/18 19:33:39 writing metadata for uncached layer 'io.projectriff.riff/riff-invoker-node'
default/hello-00001-pod-507033[build-step-build]: -----> Cloud Foundry OpenJDK Buildpack 1.0.0-M5
default/hello-00001-pod-507033[build-step-build]: 
default/hello-00001-pod-507033[build-step-build]: -----> Node.js Buildpack 0.0.2
default/hello-00001-pod-507033[build-step-build]: -----> NodeJS 11.4.0: Contributing to layer
default/hello-00001-pod-507033[build-step-build]:        Downloading from https://nodejs.org/dist/v11.4.0/node-v11.4.0-linux-x64.tar.gz
default/hello-00001-pod-507033[build-step-build]:        Verifying checksum
default/hello-00001-pod-507033[build-step-build]:        Expanding to /layers/org.cloudfoundry.buildpacks.nodejs/node
default/hello-00001-pod-507033[build-step-build]:        Writing NODE_HOME to shared
default/hello-00001-pod-507033[build-step-build]:        Writing NODE_ENV to shared
default/hello-00001-pod-507033[build-step-build]:        Writing NODE_MODULES_CACHE to shared
default/hello-00001-pod-507033[build-step-build]:        Writing NODE_VERBOSE to shared
default/hello-00001-pod-507033[build-step-build]:        Writing NPM_CONFIG_PRODUCTION to shared
default/hello-00001-pod-507033[build-step-build]:        Writing NPM_CONFIG_LOGLEVEL to shared
default/hello-00001-pod-507033[build-step-build]:        Writing WEB_MEMORY to shared
default/hello-00001-pod-507033[build-step-build]:        Writing WEB_CONCURRENCY to shared
default/hello-00001-pod-507033[build-step-build]: -----> riff Buildpack 0.2.0-BUILD-SNAPSHOT
default/hello-00001-pod-507033[build-step-build]: -----> riff Node Invoker 0.1.0: Reusing cached layer
default/hello-00001-pod-507033[build-step-build]: -----> NodeJS hello.js: Reusing cached layer
default/hello-00001-pod-507033[build-step-build]: -----> Process types:
default/hello-00001-pod-507033[build-step-build]:        web:      node /layers/io.projectriff.riff/riff-invoker-node/server.js
default/hello-00001-pod-507033[build-step-build]:        function: node /layers/io.projectriff.riff/riff-invoker-node/server.js
default/hello-00001-pod-507033[build-step-build]: 
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:45 caching unexported layer 'org.cloudfoundry.buildpacks.nodejs/4ef7dea131453da3a93cc1f32bff948da8953958dcbe3b413debae8bb41aa7a0'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:45 caching launch layer 'org.cloudfoundry.buildpacks.nodejs/node' with sha 'sha256:591279fb5d9e451b134c112b86d459baf2f6143cc8628af6969073380cec93d6'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:45 removing uncached layer 'io.projectriff.riff/function'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:45 removing uncached layer 'io.projectriff.riff/riff-invoker-node'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 adding layer 'app' with diffID 'sha256:efac5e63c5d934a97469a48396a87e93ea3ccc1c9ec9a6e916347e5f28b99bd8'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 adding layer 'config' with diffID 'sha256:788d039dca2f3950b3dbb1806d80588af4ca3a0cda5f1d2f8eed700fe3c87957'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 reusing layer 'launcher' with diffID 'sha256:2ad3c2c97afc88259b030858502967f39de147e748dc42b859b50091262d8049'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 reusing layer 'org.cloudfoundry.buildpacks.nodejs/node' with diffID 'sha256:591279fb5d9e451b134c112b86d459baf2f6143cc8628af6969073380cec93d6'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 reusing layer 'io.projectriff.riff/function' with diffID 'sha256:40bb43c93848c7cd6d9491c81f374303c0c5947024ad308848df0a3077222556'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 reusing layer 'io.projectriff.riff/riff-invoker-node' with diffID 'sha256:7e6b44a5be0d79fbd3f3e934f416adfe52a12f2ef3aa66f20ba10239be4ef6b1'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 setting metadata label 'io.buildpacks.lifecycle.metadata'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 setting env var 'PACK_LAYERS_DIR=/layers'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 setting env var 'PACK_APP_DIR=/workspace'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 setting entrypoint '/lifecycle/launcher'
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 setting empty cmd
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 writing image
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 existing blob: sha256:01e734c850498f929b8fb427f845545d3ebf3165afdb77c85a9f7dcbda1adc60
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 existing blob: sha256:7308e914506c09fa6d2242368545f55462e024f785e21b21b3e90403081a9336
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 existing blob: sha256:7ade611080482d0fcaa6840b4df8352d01b8a3018b30f762a536140cd8dffcee
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:b964be986659b0d5eaae45bbb22fc179096ef8f8f49d9dfc2d8f6c2a8920c6f6
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:2da8bfb3b5b741820e6cb29a71f66e8d944ddad2d00c6dc1e31461120ed39e46
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:7f6e268c4bf3c282c066a17015e6c89268476592bb092a4577b6768790250dc3
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:705054bc3f5bd722eb8f026532447fac897c521d8906eb36e79a60d0fb0606fa
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:80e339c0631fb56471f967a9838454f62212fcf097b3424152b3a2cd266f52aa
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:99bad2b50436a694eaa4c3c0fb337e6a1f96e19783a0dec18513247ec03db603
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:38e2e6cd5626f31cea1a0a5751a9a7e6564c589a3388dcf84f00d4bb98146844
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:2501aaff82c2d492dc3f4fd4f526fd3c2e7fd090297559566733f170d92d692f
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:4c51b7d9e9ea44f5e1a432b04fd1d3a2accbcc8e8c2ba7455155a6661c868fb8
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:d3d2d352c91dfa8784df6da49f645c24b89c98b1ceee3d8dc0dc183073d94932
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:c7051e0695642c5bf01467a4a64106cabfa20e57fee91b31ee73f7308bccf5bd
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 existing blob: sha256:09b3ec4f3bede08b94d415ed2318e8766fb189bf31e69c9ed5d5db5055982f07
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 pushed blob sha256:70b4a718f3bfc891e5bcbb6c34a4ed6deb6e1df94aad0a2c293b6091ba69f2f3
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:47 pushed blob sha256:911a4ae6fad92781a6fad3bb5f7557bbd993ef4c6145261745ae314644f0d4f6
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:48 
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:48 index.docker.io/trisberg/hello:bad: digest: sha256:cfdce5b873fd8eb338b041b075e7baaeee49a07a1601282339200fb64753f29f size: 2856
default/hello-00001-pod-507033[build-step-export]: *** Image: trisberg/hello:bad@sha256:cfdce5b873fd8eb338b041b075e7baaeee49a07a1601282339200fb64753f29f
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: internal/modules/cjs/loader.js:605
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     throw err;
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     ^
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: 
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]: Error: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at executeUserCode (internal/bootstrap/node.js:342:17)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startExecution (internal/bootstrap/node.js:276:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at startup (internal/bootstrap/node.js:227:5)
default/hello-00001-deployment-648f5b84f7-9srw2[user-container]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Error: function creation failed: RevisionFailed: Revision "hello-00001" failed with message: "Container failed with: internal/modules/cjs/loader.js:605\n    throw err;\n    ^\n\nError: Cannot find module '/layers/io.projectriff.riff/riff-invoker-node/server.js'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:25)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)\n    at executeUserCode (internal/bootstrap/node.js:342:17)\n    at startExecution (internal/bootstrap/node.js:276:5)\n    at startup (internal/bootstrap/node.js:227:5)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)\n".
```

Looking at the image the invoker layer seems to be missing:

```
pack@608d54079f34:/workspace$ ls -R /layers/io.projectriff.riff/
/layers/io.projectriff.riff/:
function

/layers/io.projectriff.riff/function:
env.launch

/layers/io.projectriff.riff/function/env.launch:
FUNCTION_URI.override
```

I'm not sure what is going on here or how this original image was created but it seems that we need to check these layers.

I see this:
```
default/hello-00001-pod-507033[build-step-export]: 2019/02/18 19:33:46 reusing layer 'io.projectriff.riff/riff-invoker-node' with diffID 'sha256:7e6b44a5be0d79fbd3f3e934f416adfe52a12f2ef3aa66f20ba10239be4ef6b1'
```
but AFAICT this layer does not contain the invoker.

**Comment by ericbottard** [comment] 2019-02-19 10:00
Was the image built from a previous image? Can you reproduce generating such a bad image?

My bet here would be that there is some caching issue where the analyzer *thinks* that the buildpack did some work (copying the invoker) when it actually didn't. We've seen that already when a directory (which is the marker for use cache / don't use cache) was created as a side effect but that wasn't intended.

What worries me though, is that this scenario is tested in the integration tests of the builder project.

**Comment by trisberg** [comment] 2019-02-19 14:11
I haven't been able to reproduce this from scratch. The bad image was created by a riff build at some point. Maybe we just need to just keep an eye on this and see if it happens again with different image. Also, maybe the buildpack team can look at the image to see if they can spot anything abnormal.

**Comment by ericbottard** [comment] 2019-02-20 15:11
It seems that the invoker ended up in `/workspace`, where it shouldn't be:

```
docker run -it trisberg/hello:bad` /bin/bash
ls -al 
ls -al
total 24
drwxr-xr-x 1 root root 4096 Feb 20 11:24 .
drwxr-xr-x 1 root root 4096 Feb 20 15:09 ..
drwxr-xr-x 8 pack pack 4096 Jan  1  1970 .git
-rw-r--r-- 1 pack pack   35 Jan  1  1970 hello.js
drwxr-xr-x 3 root root 4096 Feb 20 11:24 io.projectriff.riff
-rw-r--r-- 1 pack pack   49 Jan  1  1970 riff.toml
```

**Comment by scothis** [comment] 2019-08-15 01:02
Closing because we haven't seen this again. Please reopen if that's not true.

**Closed by scothis** 2019-08-15 01:02 UTC
